id: P008025
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:19.837454
source_metadata:
  id: bdr:W22035
  title: ཚ་བ་མདའ་རྫོང་།
  author: ''
  volumes:
    be6916a3dced45f9b2b623228fe6ebf3:
      image_group_id: I1KG18057
      title: Volume 1 of tsha ba mda' rdzong /
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
