id: P008025
initial_creation_type: ocr
source_metadata:
  id: bdr:W22035
  title: ཚ་བ་མདའ་རྫོང་།
  author: ''
  volumes:
    8268ec1a1e1d44a8a8d8ac5099a7a45f:
      image_group_id: I1KG18057
      title: ''
      volume_number: 1
      total_pages: 226
ebook_metadata:
  title: ཚ་བ་མདའ་རྫོང་།
  author: ''
  sku: P008025
  cover: cover.jpg
  layers:
  - pagination
