id: IA203296B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T00:49:06+00:00'
last_modified: '2022-06-08T17:54:03.262196+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22035
  title: ཚ་བ་མདའ་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    57BB:
      image_group_id: I1KG18057
      title: Volume 1 of tsha ba mda' rdzong /
      total_pages: 226
      order: 1
      base_file: 57BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
